/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: game.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "game.pb-c.h"
void   net_command__init
                     (NetCommand         *message)
{
  static const NetCommand init_value = NET_COMMAND__INIT;
  *message = init_value;
}
size_t net_command__get_packed_size
                     (const NetCommand *message)
{
  assert(message->base.descriptor == &net_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t net_command__pack
                     (const NetCommand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &net_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t net_command__pack_to_buffer
                     (const NetCommand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &net_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NetCommand *
       net_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NetCommand *)
     protobuf_c_message_unpack (&net_command__descriptor,
                                allocator, len, data);
}
void   net_command__free_unpacked
                     (NetCommand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &net_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   login__init
                     (Login         *message)
{
  static const Login init_value = LOGIN__INIT;
  *message = init_value;
}
size_t login__get_packed_size
                     (const Login *message)
{
  assert(message->base.descriptor == &login__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t login__pack
                     (const Login *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &login__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t login__pack_to_buffer
                     (const Login *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &login__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Login *
       login__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Login *)
     protobuf_c_message_unpack (&login__descriptor,
                                allocator, len, data);
}
void   login__free_unpacked
                     (Login *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &login__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   net_return__init
                     (NetReturn         *message)
{
  static const NetReturn init_value = NET_RETURN__INIT;
  *message = init_value;
}
size_t net_return__get_packed_size
                     (const NetReturn *message)
{
  assert(message->base.descriptor == &net_return__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t net_return__pack
                     (const NetReturn *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &net_return__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t net_return__pack_to_buffer
                     (const NetReturn *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &net_return__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NetReturn *
       net_return__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NetReturn *)
     protobuf_c_message_unpack (&net_return__descriptor,
                                allocator, len, data);
}
void   net_return__free_unpacked
                     (NetReturn *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &net_return__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   return_public_key__init
                     (ReturnPublicKey         *message)
{
  static const ReturnPublicKey init_value = RETURN_PUBLIC_KEY__INIT;
  *message = init_value;
}
size_t return_public_key__get_packed_size
                     (const ReturnPublicKey *message)
{
  assert(message->base.descriptor == &return_public_key__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t return_public_key__pack
                     (const ReturnPublicKey *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &return_public_key__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t return_public_key__pack_to_buffer
                     (const ReturnPublicKey *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &return_public_key__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReturnPublicKey *
       return_public_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReturnPublicKey *)
     protobuf_c_message_unpack (&return_public_key__descriptor,
                                allocator, len, data);
}
void   return_public_key__free_unpacked
                     (ReturnPublicKey *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &return_public_key__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   return_is_login_success__init
                     (ReturnIsLoginSuccess         *message)
{
  static const ReturnIsLoginSuccess init_value = RETURN_IS_LOGIN_SUCCESS__INIT;
  *message = init_value;
}
size_t return_is_login_success__get_packed_size
                     (const ReturnIsLoginSuccess *message)
{
  assert(message->base.descriptor == &return_is_login_success__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t return_is_login_success__pack
                     (const ReturnIsLoginSuccess *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &return_is_login_success__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t return_is_login_success__pack_to_buffer
                     (const ReturnIsLoginSuccess *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &return_is_login_success__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReturnIsLoginSuccess *
       return_is_login_success__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReturnIsLoginSuccess *)
     protobuf_c_message_unpack (&return_is_login_success__descriptor,
                                allocator, len, data);
}
void   return_is_login_success__free_unpacked
                     (ReturnIsLoginSuccess *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &return_is_login_success__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue net_command__command__enum_values_by_number[2] =
{
  { "GET_PUBLIC_KEY", "NET_COMMAND__COMMAND__GET_PUBLIC_KEY", 0 },
  { "LOGIN", "NET_COMMAND__COMMAND__LOGIN", 1 },
};
static const ProtobufCIntRange net_command__command__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex net_command__command__enum_values_by_name[2] =
{
  { "GET_PUBLIC_KEY", 0 },
  { "LOGIN", 1 },
};
const ProtobufCEnumDescriptor net_command__command__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "NetCommand.Command",
  "Command",
  "NetCommand__Command",
  "",
  2,
  net_command__command__enum_values_by_number,
  2,
  net_command__command__enum_values_by_name,
  1,
  net_command__command__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor net_command__field_descriptors[3] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(NetCommand, command),
    &net_command__command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hasParameter",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(NetCommand, hasparameter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parameterLength",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(NetCommand, parameterlength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned net_command__field_indices_by_name[] = {
  0,   /* field[0] = command */
  1,   /* field[1] = hasParameter */
  2,   /* field[2] = parameterLength */
};
static const ProtobufCIntRange net_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor net_command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NetCommand",
  "NetCommand",
  "NetCommand",
  "",
  sizeof(NetCommand),
  3,
  net_command__field_descriptors,
  net_command__field_indices_by_name,
  1,  net_command__number_ranges,
  (ProtobufCMessageInit) net_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor login__field_descriptors[2] =
{
  {
    "account",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Login, account),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Login, password),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned login__field_indices_by_name[] = {
  0,   /* field[0] = account */
  1,   /* field[1] = password */
};
static const ProtobufCIntRange login__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor login__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Login",
  "Login",
  "Login",
  "",
  sizeof(Login),
  2,
  login__field_descriptors,
  login__field_indices_by_name,
  1,  login__number_ranges,
  (ProtobufCMessageInit) login__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue net_return__command_return__enum_values_by_number[2] =
{
  { "RETURN_PUBLIC_KEY", "NET_RETURN__COMMAND_RETURN__RETURN_PUBLIC_KEY", 0 },
  { "RETURN_IS_LOGIN_SUCCESS", "NET_RETURN__COMMAND_RETURN__RETURN_IS_LOGIN_SUCCESS", 1 },
};
static const ProtobufCIntRange net_return__command_return__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex net_return__command_return__enum_values_by_name[2] =
{
  { "RETURN_IS_LOGIN_SUCCESS", 1 },
  { "RETURN_PUBLIC_KEY", 0 },
};
const ProtobufCEnumDescriptor net_return__command_return__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "NetReturn.CommandReturn",
  "CommandReturn",
  "NetReturn__CommandReturn",
  "",
  2,
  net_return__command_return__enum_values_by_number,
  2,
  net_return__command_return__enum_values_by_name,
  1,
  net_return__command_return__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor net_return__field_descriptors[3] =
{
  {
    "commandReturn",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(NetReturn, commandreturn),
    &net_return__command_return__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hasReturnMessage",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(NetReturn, hasreturnmessage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "returnMessageLength",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(NetReturn, returnmessagelength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned net_return__field_indices_by_name[] = {
  0,   /* field[0] = commandReturn */
  1,   /* field[1] = hasReturnMessage */
  2,   /* field[2] = returnMessageLength */
};
static const ProtobufCIntRange net_return__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor net_return__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NetReturn",
  "NetReturn",
  "NetReturn",
  "",
  sizeof(NetReturn),
  3,
  net_return__field_descriptors,
  net_return__field_indices_by_name,
  1,  net_return__number_ranges,
  (ProtobufCMessageInit) net_return__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor return_public_key__field_descriptors[1] =
{
  {
    "publicKey",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReturnPublicKey, publickey),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned return_public_key__field_indices_by_name[] = {
  0,   /* field[0] = publicKey */
};
static const ProtobufCIntRange return_public_key__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor return_public_key__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ReturnPublicKey",
  "ReturnPublicKey",
  "ReturnPublicKey",
  "",
  sizeof(ReturnPublicKey),
  1,
  return_public_key__field_descriptors,
  return_public_key__field_indices_by_name,
  1,  return_public_key__number_ranges,
  (ProtobufCMessageInit) return_public_key__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor return_is_login_success__field_descriptors[1] =
{
  {
    "success",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ReturnIsLoginSuccess, success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned return_is_login_success__field_indices_by_name[] = {
  0,   /* field[0] = success */
};
static const ProtobufCIntRange return_is_login_success__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor return_is_login_success__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ReturnIsLoginSuccess",
  "ReturnIsLoginSuccess",
  "ReturnIsLoginSuccess",
  "",
  sizeof(ReturnIsLoginSuccess),
  1,
  return_is_login_success__field_descriptors,
  return_is_login_success__field_indices_by_name,
  1,  return_is_login_success__number_ranges,
  (ProtobufCMessageInit) return_is_login_success__init,
  NULL,NULL,NULL    /* reserved[123] */
};
